### ISSUE TITLE
undefined method `get' for :api_caller:Symbol

### ISSUE THREAD

**Issue by mariowise** [platanus/dialers#1]
Hola, estuve probando la gema y con un pequeño ejemplo me arroja el error que muestro a final

```
require 'dialers'

class ApiCaller < Dialers::Caller

    TIMEOUT_IN_SECONDS = 10

  setup_api(url: "https://stg.surbtc.com/api/v1") do |faraday|
    faraday.request :json
    faraday.request :request_headers, accept: "application/json"
    faraday.response :json
    faraday.adapter :net_http
    faraday.options.timeout = TIMEOUT_IN_SECONDS
    faraday.options.open_timeout = TIMEOUT_IN_SECONDS
  end

end

class Api < Dialers::Wrapper
    api_caller { ApiCaller }

    def self.all 
        req = api_caller.get("markets").as_received
        return req if !req
        return req
    end
end

puts Api.all
```

Alguna idea de porqué podría estar pasando, ¿hay algo que veo mal?

```
test_ground.rb:22:in `all': undefined method `get' for :api_caller:Symbol (NoMethodError)
Did you mean?  gets
               gem
    from test_ground.rb:28:in `<main>'
```

**Comment by mariowise** [comment]
Pude hacerlo funcionar considerando que debe ser utilizado un método de **instancia de la clase Api** y además en el `api_caller { ApiCaller.new }` había que agregar la llamada al constructor. Lo cual no vi en el Readme.
